
development:
  adapter: postgresql
  encoding: unicode
  database: robot_world_dev
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: robot_world_test
  pool: 5
  username: postgres
  password: postgres